# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Instal & Build
        run: |
          npm install
          npm run build
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public
          token: ${{ secrets.GH_TOKEN }}
          repository-name: afi-team/afi-team.github.io
          
      - name: Init Aliyun OSS
        uses: jerray/setup-aliyun-cli-action@v1.0.0
        with:
          aliyun-cli-version: '3.0.29'
          mode: AK
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          region: ${{ secrets.ALIYUN_REGION }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Deploy to Aliyun OSS
        run: aliyun oss cp ./public oss://afi-team/ -r -u

